// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// leds_px_pusher //
// -------------- //

#define leds_px_pusher_wrap_target 0
#define leds_px_pusher_wrap 3

#define leds_px_pusher_offset_entry_point 0u

static const uint16_t leds_px_pusher_program_instructions[] = {
            //     .wrap_target
    0x7063, //  0: out    null, 3         side 0     
    0x6001, //  1: out    pins, 1                    
    0x7964, //  2: out    null, 4         side 1 [1] 
    0xb042, //  3: nop                    side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program leds_px_pusher_program = {
    .instructions = leds_px_pusher_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config leds_px_pusher_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + leds_px_pusher_wrap_target, offset + leds_px_pusher_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

